accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUP.as_view(),name='signup'),
    path('users/',views.ViewUsers.as_view(),name='users')
]

my_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from blog.views import Home,HomeBlog,TestPage,ThanksPage,PostDetail
from posts.views import (CreatePost,
                         ViewPost,
                         UpdatePost,
                         DeletePost)
from categories.views import (CreateCategory,
                         UpdateCategory,
                         DeleteCategory,
                         ViewCategories)
from tags.views import (ViewTag,
                         CreateTag,
                         UpdateTag,
                         DeleteTag)
from settings.views import (UpdateSetting,
                            ViewSetting,
                            CreateSetting,
                            DeleteSetting)
urlpatterns = [
    path('admin/', admin.site.urls),
    #accounts
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',TestPage.as_view(), name='test'),
    path('thanks/',ThanksPage.as_view(), name='thanks'),
    #posts
    path('post/create/',CreatePost.as_view(), name='create_post'),
    path('view/posts',ViewPost.as_view(), name='view_post'),
    path('post/update/(?P<pk>\d+)/$/',UpdatePost.as_view(), name='update_post'),
    path('post/delete/(?P<pk>\d+)/$/',DeletePost.as_view(), name='delete_post'),
    #category
    path('category/create/',CreateCategory.as_view(), name='create_category'),
    path('category/update/(?P<pk>\d+)/$/',UpdateCategory.as_view(), name='update_category'),
    path('category/delete/(?P<pk>\d+)/$/',DeleteCategory.as_view(), name='delete_category'),
    path('categories/',ViewCategories.as_view(), name='view_categories'),
    #Tags
    path('view/tags',ViewTag.as_view(), name='view_tag'),
    path('tag/create/',CreateTag.as_view(), name='create_tag'),
    path('tag/update/(?P<pk>\d+)/$/',UpdateTag.as_view(), name='update_tag'),
    path('tag/delete/(?P<pk>\d+)/$/',DeleteTag.as_view(), name='delete_tag'),
    #Setting
    path('create/setting/',CreateSetting.as_view(), name='create_setting'),
    path('view/setting',ViewSetting.as_view(), name='view_setting'),
    path('edit/setting/(?P<pk>\d+)/$/',UpdateSetting.as_view(),name='update_setting'),
    path('setting/delete/(?P<pk>\d+)/$/',DeleteSetting.as_view(), name='delete_setting'),
    #HOME
    path('',Home.as_view(),name='home'),
    path('home/blog',HomeBlog.as_view(),name='home_blog'),
    path('post/detail',PostDetail.as_view(),name='post_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <script src="{% static '/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home_blog' %}">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
    <ul class="navbar-nav my-2 my-lg-0">
      {% if user.is_authenticated %}
      <li class="mr-sm-2">
        <a class="nav-link" href="{% url 'accounts:logout'%}">Log Out</a>
      </li>
      {% else %}
      <li class="mr-sm-2">
        <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
      </li>
      <li class="my-2 my-sm-0">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

        {% block content %}

        {% endblock %}

  </body>
</html>

templates/header.html
<div id="app" class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Navbar</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricingg</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#S">Register</a>
      </li>
    </ul>
  </nav>
</div>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      {% include 'index.html' %}
    </div>
    <div class="col-sm-8 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h4 class='bg-info'>Home</h4>
      </div>
      <div class="panel panel-default">

      <h1>HOME</h1>


      </div>


    </div>
    </div>



  </div>
</div>
{% endblock %}

templates/index.html
<div class="container">
    <ul class="list-group">
      <li class="list-group-item">
        <a href="{% url 'home' %}">Home</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'create_post' %}">Create new post</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'create_category' %}">Create new category</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'view_categories' %}">Categories</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'view_post' %}">All Post</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'create_tag' %}">Create Tag</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'view_tag' %}">Tags</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'accounts:signup' %}">Create new user</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'accounts:users' %}">Users</a>
      </li>
      <li class="list-group-item">
          <a href="{% url 'view_setting' %}">Setting</a>
      </li>
    </ul>
  <br>
</div>

templates/test.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">

      {% include 'index.html' %}

    </div>
    <div class="col-sm-8 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h4 class='bg-info'>Create a new Tag</h4>

      </div>
    <div class="panel-body">
      <form class="form-control" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input class="btn btn-success" type="submit" name="" value="submit">
        </div>
      </form>
    </div>
    </div>

    </div>

  </div>
</div>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
  <h1>Thanks for visting come back soon!</h1>
{% endblock %}